### ISSUE TITLE
Unknown becomes NSW and Auckland becomes Aus

### ISSUE THREAD

**Issue by surgissant** [runapp-aus/strayr#111]
![image](https://github.com/runapp-aus/strayr/assets/20392015/f31018ff-d59b-4cde-8aef-b6a862c95e3e)

Had to turn off fuzzy matching :(

**Comment by MattCowgill** [comment]
Hmm that's pretty bad @surgissant 

I think maybe I should turn down the threshold for a fuzzy match (ie. be a bit stricter)

**Comment by MattCowgill** [comment]
Turning down `max_dist` (the threshold for fuzzy matching) does the trick here 

``` r
library(tidyverse)
tibble(State = c("VIC",
                 "Unknown",
                 "WA",
                 "NSW",
                 "SA",
                 "QLD",
                 "ACT",
                 "TAS",
                 "Hong Kong",
                 "Auckland")) |> 
  mutate(State_ = strayr::clean_state(State,
                                      max_dist = 0.2))
#> # A tibble: 10 × 2
#>    State     State_
#>    <chr>     <chr> 
#>  1 VIC       Vic   
#>  2 Unknown   <NA>  
#>  3 WA        WA    
#>  4 NSW       NSW   
#>  5 SA        SA    
#>  6 QLD       Qld   
#>  7 ACT       ACT   
#>  8 TAS       Tas   
#>  9 Hong Kong <NA>  
#> 10 Auckland  <NA>
```

<sup>Created on 2024-01-31 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

I'll reduce the default `max_dist` to 0.2 from 0.4

**Comment by surgissant** [comment]
Legend. Thankyou, I should have read the docs!
