### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by wfmackey** [runapp-aus/strayr#21]
As we move into more functions -- eg #18 -- dependencies will become more of an issue. For example, whether `abscorr` requires `tidyverse` (or specific packages/functions), or `data.table`, or both, or neither, etc. 

I'm not hugely knowledgeable in this area. Does anyone have any suggestions/thoughts about a dependency policy?

**Comment by mrjoh3** [comment]
I don't have a strong opinion but I think the less dependencies the better. Maybe we just need a rough guide of sticking with already imported packages "as much as possible". But I am also curious to hear other peoples opinions.

**Comment by wfmackey** [comment]
Closing this. Feel free to re-open if you have _thoughts_.
