### ISSUE TITLE
Rename package `strayr`, port `strayr` functions, and update package documentation for changes

### ISSUE THREAD

**Issue by wfmackey** [runapp-aus/strayr#35]
re #20 . @MattCowgill will port `mattcowgill/strayr` functions.

- [x] port `strayr` functions
- [x] rename package

**Comment by MattCowgill** [comment]
FYI @bryceroney as a contributor to `strayr`, just letting you know that we're going to:
1. Rename `abscorr` to `strayr`; and
2. Bring in all the functions from the existing `strayr` package (including yours related to public holidays) to this package.

**Comment by bryceroney** [comment]
No dramas @MattCowgill. I'll put in a PR to update the pkgdown site to include the references.

**Comment by wfmackey** [comment]
Repo renamed! Hopefully it won't break anything, but I am sorry when it inevitably does.

**Comment by daviddiviny** [comment]
I've re-opened this issue @wfmackey as there seem to be a bunch of `strayr` eferences to the old name of `abscorr` (e.g. [here](https://github.com/runapp-aus/strayr/blob/64a8fa628fc8943eca7a61fc07e1e3eb3b9b38cb/DESCRIPTION#L1)). 

I'm not sure of the systematic way to do this but this [blogpost](https://www.njtierney.com/post/2017/10/27/change-pkg-name/) from runapp-er njtierney looks useful.

**Comment by wfmackey** [comment]
This has been done in #42

**Comment by daviddiviny** [comment]
Does [Matt's github](https://github.com/MattCowgill/strayr) somehow need to mirror the runapp-aus version?

**Comment by MattCowgill** [comment]
not sure how to do that... rename my existing repo and fork this repo?

**Comment by bryceroney** [comment]
You could archive the repository, given the README points people to the new repo.
