### ISSUE TITLE
Move documentation examples to vignettes

### ISSUE THREAD

**Issue by bryceroney** [runapp-aus/strayr#41]
I was thinking as the functionality of the package grows, we could end up with a pretty long README so we could move them to vignettes and then reference in the README.

Any issues with that?

**Comment by MattCowgill** [comment]
It'd be good if the README still gives a sense of what the package can do, but I agree it doesn't need comprehensive documentation of every function

**Comment by daviddiviny** [comment]
Agree. 

Maybe it should provide an overview of the overall structure of the package and the families of functions within:
- Data
- Cleaning
- etc

**Comment by bryceroney** [comment]
Yes, agreed with both above. I think the Tidyverse packages find a good balance between detail and summary.

**Comment by bryceroney** [comment]
Have been thinking also, some of the documentation could be handled by the actual reference documentation, e.g. the public holidays data.

**Comment by wfmackey** [comment]
I agree with all of the above. Maybe:

- README: outline of package, summary of families of functions
  - 'hey these functions/datasets exist'
- vignettes: detailed (but not exhaustive) demonstrations of function/dataset use (similar to what is in README now)
  - 'hey this is how you might use the functions/datasets, or how you would contribute to this package'.
- package documentation: exhaustive detail.

**Comment by mrjoh3** [comment]
In `pkgage` down the general use case is, the readme is for installation instructions and enough detail for people on github. Then you have a vignette with the package name that has more detailed information, then additional vignettes for specific topics. 

I thought I had setup a vignette with the package name but had not added content yet. I will get this setup and report back

**Comment by wfmackey** [comment]
Thanks @mrjoh3, @bryceroney and @MattCowgill for putting this together in #49 . Now to write some more vignettes!
