### ISSUE TITLE
Add function to pull greatest level of defined detail from 'nfd' code

### ISSUE THREAD

**Issue by martintburgess** [runapp-aus/strayr#44]
We have a use case to take a "not further defined" ANZSIC and ANZSCO code or name and get the highest level of defined detail. 

For example, from '2510' we would want "251" and from "Furniture Manufacturing, nfd" we would want "Furniture Manufacturing".

Appreciate it is usually just lopping off some characters at the end but could be helpful to include here. 

cc @daviddiviny

**Comment by wfmackey** [comment]
Good idea, @martintburgess. So maybe a `clean_nfd` or `validate_nfd` or `get_valid_nfd` function that:

```r
> clean_nfd("Furniture Manufacturing, nfd")
[1]  "Furniture Manufacturing, nfd"
> clean_nfd("2510")
[1]  "251"
```

and 

```r
> clean_nfd("Managers, nfd ")
[1]  "Managers"
> clean_nfd("100000")
[1]  "1"
```

Is that what you had in mind?

**Comment by martintburgess** [comment]
Yes, that looks great thanks @wfmackey. Probably useful if it can take a vector input as well: 

```
> clean_nfd(c("Managers, nfd ", "2510")
[1]  c("Managers", "251")
```

**Comment by bennywee** [comment]
Hey @wfmackey, I'm getting a github authentication issue when I try to push commits up to a new branch directly.

Is the appropriate workflow:

1) Fork
2) Commit + push
3) PR

Or is there a way to authenticate + contribute directly to the repo?

**Comment by wfmackey** [comment]
Hi @bennywee, my workflow tends to be:

New branch → commit directly to that branch → PR when done. 

But forking should work, too. 

Your authentication issue may need me to add you to the runapp-aus GitHub group. I'll do that now!

**Comment by wfmackey** [comment]
and @bennywee maybe we should work through this issue on the Discussions tab? (could be useful for others!)

**Comment by bennywee** [comment]
Great, thanks for that @wfmackey .  Turns out I also needed to set up SSH/PAT since github has removed password authentication. Happy to write up something for the discussion board if this is useful! 

Back to clean_nfd: I have a basic version of the function [here.](https://github.com/runapp-aus/strayr/blob/clean-nfd-bennywee/R/clean_nfd.R) I've written it basically to remove instances of ", nfd" and trailing zeroes in strings. It will only take in a vector of strings at the moment - can extend it to accept a full dataframe if that is more useful.

**Comment by wfmackey** [comment]
`clean_nfd` looks great, @bennywee. Are you looking to add the ability to detect and remove trailing zeros as well? eg

```
clean_nfd("2510")
[1]  "251"
```

(otherwise I'm happy to add that when you submit a PR). Great stuff.

And re the SSH/PAT -- yes! Adding a note about that would be wonderful.

**Comment by wfmackey** [comment]
Nice work on the tests, too. Can you submit a PR and we'll get it merged!

**Comment by bennywee** [comment]
Hey @martintburgess , the `clean_nfd` function has been merged to the main branch (thanks @wfmackey!) Do you want to have a go and if you're happy I can close this issue.

**Comment by martintburgess** [comment]
Thanks @bennywee, I will give this a go tomorrow, it's #71 - is that right?

**Comment by bennywee** [comment]
@martintburgess yep that's the one! :)

**Comment by martintburgess** [comment]
Works great, thanks @bennywee and @wfmackey. I'll close.
