### ISSUE TITLE
Do structures need year/version suffixes?

### ISSUE THREAD

**Issue by wfmackey** [runapp-aus/strayr#51]
ANZSCO is getting a decent update at the end of 2021, likely (surely) to be used for the 2021 Census: https://www.abs.gov.au/articles/updating-australian-and-new-zealand-standard-classification-occupations. The ABS have also indicated that updates will be 'more regular and timely'.

Updating the `anzsco` object to include new classifications/remove old ones will be necessary, but will be backwards incompatible. If this is happening every year, it'll be a problem. 

So, like the current `absmapsdata` ASGS structures (`sa12011`, `sa12016`, etc), should `anzsco` et al get a year suffix?

The benefits of this would be that old code works for more than a year. The costs are that you need to type a few more letters, and the 'last updated' year might be a bit confusing? We could keep an un-suffixed structure, eg `anzsco`, that defaults to the latest version; although that would introduce the same issues. 

I think I'm leaning towards having a year suffix for all structures, and not having an un-suffixed version. Keen to hear thoughts.

**Comment by MattCowgill** [comment]
So there are two questions:

1. Should `anzsco` et al get a year suffix? 
2. Should `anzsco` et al still have an un-suffixed version. 

I reckon the clear answer to (1) is 'yes'. On (2) I am torn. Leaning towards yes but not sure

**Comment by wfmackey** [comment]
Agree re (1). 

If we allow (2), users will _use_ un-suffixed versions that will mean their code will become outdated/problematic in unpredictable ways as ANZSCO is updated. So, should we allow that potentially unsafe behaviour?

**Comment by MattCowgill** [comment]
Yeah good point... OK I guess I'm leaning towards `no` on (2) then but still not quite sure

**Comment by daviddiviny** [comment]
I vote no on 2. I really like the absmapsdata convention.

**Comment by wfmackey** [comment]
Safety first it is.

**Comment by MattCowgill** [comment]
I'm happy with that

**Comment by wfmackey** [comment]
This might allow for neater correspondence functions between two times, eg `get_correspondence(anzsco2006, anzsco2021)`
