### ISSUE TITLE
Tiny but annoying typo in the readme

### ISSUE THREAD

**Issue by charlescoverdale** [runapp-aus/strayr#80]
Hey Will, 

I spent 10 minutes wondering why my code wouldn't work this arvo - then realized the line at the end of the readme 'See ?strayr::read_absmaps.' should actually be 'See ?strayr::read_absmap'

Tiny issue - but thought I'd flag.

Thanks!

C

**Comment by MattCowgill** [comment]
thanks @charlescoverdale, I've fixed it in a PR
