### ISSUE TITLE
In the ANZSIC 2006 table, subdivision 69 is named incorrectly

### ISSUE THREAD

**Issue by aaronw22** [runapp-aus/strayr#91]
In the data.frame `anzsic2006`, subdivision 69, which has name "Professional, Scientific and Technical Services (Except Computer System Design and Related" is missing a word at the end as the correct ANZSIC name is "Professional, Scientific and Technical Services (Except Computer System Design and Related Services)".

**Comment by williamlai2** [comment]
It looks like the raw data is created here: https://github.com/runapp-aus/strayr/blob/master/data-raw/create_anzsic2006.R but originally comes from here: https://raw.githubusercontent.com/asiripanich/anzsic/master/anzsic_2006.csv

**Comment by MattCowgill** [comment]
Well spotted @aaronw22! 

I'm short on time this week so can't fix this - if anyone else is able, I'd gladly review a pull request

**Comment by williamlai2** [comment]
I put in a pull request at the source (which would fix this issue). Otherwise the source could be changed to something else.

**Comment by peteowen1** [comment]
this issue can be closed
