### ISSUE TITLE
Strayr imports `purrr::list_rbind()` which is only in new versions of purrr

### ISSUE THREAD

**Issue by MattCowgill** [runapp-aus/strayr#96]
A recent PR (@baslat's?) imports `purrr::list_rbind()`. This function is only precent in recent versions of purrr -- I think 1.0+. I just got an error trying to use an older version of purrr and strayr together. 

Two options: 
1) Be explicit in strayr's DESCRIPTION that it requires purrr >= 1.0.0 
2) Remove the list_rbind() dependency 

I favour option 1 but wanted to post an issue to see if there's any disagreement

**Comment by baslat** [comment]
It can use `map_dfr` instead of `map` and `list_rbind` if that is more backwards compatible.

**Comment by MattCowgill** [comment]
The downside then is that `map_dfr` is deprecated (or at least superseded).... 
I'm inclined to leave the code as it is and just require >= 1.0.0

**Comment by baslat** [comment]
I think that is the correct approach. Only downside I can see is if people are on restrictive environments (yet somehow access GitHub) and cannot update purrr.

**Comment by MattCowgill** [comment]
Resolved https://github.com/runapp-aus/strayr/pull/106
